APP = {
    'key': 'humanitarian_access',
    'name': 'Humanitarian Access',
    'description': 'Track movement clearances, incident reports, access constraints and checkpoints.',
    'icon': '🛡️',
    'color': 'red',
    'version': '1.0',
    'entity_types': [
        {
            'name': 'Checkpoint',
            'slug': 'ha_checkpoint',
            'description': 'Known checkpoints and crossing points',
            'icon': '🚧',
            'is_lookup': True,
            'parent_slug': None,
            'fields': [
                {'name': 'checkpoint_name', 'label': 'Checkpoint Name', 'field_type': 'text',
                 'is_required': True, 'display_in_list': True},
                {'name': 'location', 'label': 'Location / Coordinates', 'field_type': 'text',
                 'is_required': True},
                {'name': 'controlling_party', 'label': 'Controlling Party', 'field_type': 'text'},
                {'name': 'is_active', 'label': 'Currently Active', 'field_type': 'boolean'},
                {'name': 'notes', 'label': 'Notes', 'field_type': 'textarea'},
            ],
        },
        {
            'name': 'Access Constraint',
            'slug': 'ha_access_constraint',
            'description': 'Areas with access restrictions',
            'icon': '🚫',
            'is_lookup': True,
            'parent_slug': None,
            'fields': [
                {'name': 'area_name', 'label': 'Area Name', 'field_type': 'text',
                 'is_required': True, 'display_in_list': True},
                {'name': 'constraint_type', 'label': 'Constraint Type', 'field_type': 'select',
                 'is_required': True, 'display_in_list': True,
                 'options': ['Full Denial', 'Partial', 'Seasonal', 'Administrative']},
                {'name': 'controlling_party', 'label': 'Controlling Party', 'field_type': 'text'},
                {'name': 'start_date', 'label': 'Start Date', 'field_type': 'date'},
                {'name': 'end_date', 'label': 'End Date', 'field_type': 'date'},
                {'name': 'last_verified', 'label': 'Last Verified', 'field_type': 'date'},
                {'name': 'notes', 'label': 'Notes', 'field_type': 'textarea'},
            ],
        },
        {
            'name': 'Movement Clearance',
            'slug': 'ha_movement_clearance',
            'description': 'Movement clearance requests and approvals',
            'icon': '📋',
            'is_lookup': False,
            'parent_slug': None,
            'fields': [
                {'name': 'clearance_date', 'label': 'Travel Date', 'field_type': 'date',
                 'is_required': True, 'display_in_list': True},
                {'name': 'origin', 'label': 'Origin', 'field_type': 'text', 'is_required': True},
                {'name': 'destination', 'label': 'Destination', 'field_type': 'text',
                 'is_required': True, 'display_in_list': True},
                {'name': 'travel_mode', 'label': 'Travel Mode', 'field_type': 'select',
                 'is_required': True,
                 'options': ['Road', 'Air', 'River', 'Other']},
                {'name': 'team_size', 'label': 'Team Size', 'field_type': 'number'},
                {'name': 'cargo_description', 'label': 'Cargo / Items', 'field_type': 'textarea'},
                {'name': 'checkpoint_used', 'label': 'Checkpoint', 'field_type': 'lookup',
                 'lookup_slug': 'ha_checkpoint'},
                {'name': 'status', 'label': 'Status', 'field_type': 'select',
                 'is_required': True, 'display_in_list': True,
                 'options': ['Pending', 'Approved', 'Denied', 'Cancelled']},
                {'name': 'approved_by', 'label': 'Approved By', 'field_type': 'text'},
                {'name': 'valid_until', 'label': 'Valid Until', 'field_type': 'date'},
                {'name': 'notes', 'label': 'Notes', 'field_type': 'textarea'},
            ],
        },
        {
            'name': 'Incident Report',
            'slug': 'ha_incident_report',
            'description': 'Security and access incidents',
            'icon': '⚠️',
            'is_lookup': False,
            'parent_slug': None,
            'fields': [
                {'name': 'incident_date', 'label': 'Incident Date', 'field_type': 'date',
                 'is_required': True, 'display_in_list': True},
                {'name': 'incident_type', 'label': 'Incident Type', 'field_type': 'select',
                 'is_required': True, 'display_in_list': True,
                 'options': ['Checkpoint Denial', 'Road Closure', 'Arrest / Detention',
                             'Threat', 'Theft', 'Vehicle Seizure', 'Other']},
                {'name': 'location_description', 'label': 'Location', 'field_type': 'text',
                 'is_required': True, 'display_in_list': True},
                {'name': 'nearest_checkpoint', 'label': 'Nearest Checkpoint', 'field_type': 'lookup',
                 'lookup_slug': 'ha_checkpoint'},
                {'name': 'severity', 'label': 'Severity', 'field_type': 'select',
                 'is_required': True,
                 'options': ['Low', 'Medium', 'High', 'Critical']},
                {'name': 'description', 'label': 'Description', 'field_type': 'textarea',
                 'is_required': True},
                {'name': 'affected_staff', 'label': 'Staff Affected', 'field_type': 'number'},
                {'name': 'reported_to_authorities', 'label': 'Reported to Authorities',
                 'field_type': 'boolean'},
                {'name': 'follow_up_required', 'label': 'Follow-up Required',
                 'field_type': 'boolean'},
                {'name': 'follow_up_notes', 'label': 'Follow-up Notes', 'field_type': 'textarea'},
            ],
        },
    ],
    'forms': [
        {
            'name': 'Movement Clearance Request',
            'description': 'Submit a movement clearance request',
            'entity_type_slug': 'ha_movement_clearance',
            'fields': ['clearance_date', 'origin', 'destination', 'travel_mode',
                       'team_size', 'cargo_description', 'checkpoint_used', 'notes'],
        },
        {
            'name': 'Incident Report Form',
            'description': 'Report a humanitarian access incident',
            'entity_type_slug': 'ha_incident_report',
            'fields': ['incident_date', 'incident_type', 'location_description',
                       'nearest_checkpoint', 'severity', 'description',
                       'affected_staff', 'reported_to_authorities',
                       'follow_up_required', 'follow_up_notes'],
        },
    ],
}
