APP = {
    'key': 'immunization_report',
    'name': 'Immunization Report',
    'description': 'Track vaccination sessions, coverage targets, cold chain equipment and adverse events.',
    'icon': '💉',
    'color': 'green',
    'version': '1.0',
    'entity_types': [
        {
            'name': 'Cold Chain Equipment',
            'slug': 'imm_cold_chain',
            'description': 'Vaccine storage equipment registry',
            'icon': '🧊',
            'is_lookup': True,
            'parent_slug': None,
            'fields': [
                {'name': 'equipment_name', 'label': 'Equipment Name', 'field_type': 'text',
                 'is_required': True, 'display_in_list': True},
                {'name': 'equipment_type', 'label': 'Type', 'field_type': 'select',
                 'is_required': True, 'display_in_list': True,
                 'options': ['Refrigerator', 'Freezer', 'Cold Box', 'Vaccine Carrier', 'Generator']},
                {'name': 'serial_number', 'label': 'Serial Number', 'field_type': 'text'},
                {'name': 'installation_date', 'label': 'Installation Date', 'field_type': 'date'},
                {'name': 'working_status', 'label': 'Status', 'field_type': 'select',
                 'is_required': True, 'display_in_list': True,
                 'options': ['Working', 'Needs Repair', 'Out of Service']},
                {'name': 'last_temperature_check', 'label': 'Last Temp Check',
                 'field_type': 'date'},
                {'name': 'min_temperature', 'label': 'Min Temp (°C)', 'field_type': 'number'},
                {'name': 'max_temperature', 'label': 'Max Temp (°C)', 'field_type': 'number'},
            ],
        },
        {
            'name': 'Coverage Target',
            'slug': 'imm_coverage_target',
            'description': 'Annual vaccination coverage targets by antigen',
            'icon': '🎯',
            'is_lookup': False,
            'parent_slug': None,
            'fields': [
                {'name': 'vaccine_type', 'label': 'Vaccine / Antigen', 'field_type': 'select',
                 'is_required': True, 'display_in_list': True,
                 'options': ['OPV', 'IPV', 'Penta', 'MCV1', 'MCV2', 'BCG',
                             'RVV', 'PCV', 'HPV', 'COVID-19', 'Other']},
                {'name': 'target_year', 'label': 'Year', 'field_type': 'number',
                 'is_required': True, 'display_in_list': True},
                {'name': 'period', 'label': 'Period', 'field_type': 'select',
                 'is_required': True,
                 'options': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                             'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Full Year']},
                {'name': 'target_count', 'label': 'Target Doses', 'field_type': 'number',
                 'is_required': True},
            ],
        },
        {
            'name': 'Vaccination Session',
            'slug': 'imm_vaccination_session',
            'description': 'Record vaccination session data',
            'icon': '📋',
            'is_lookup': False,
            'parent_slug': None,
            'fields': [
                {'name': 'session_date', 'label': 'Session Date', 'field_type': 'date',
                 'is_required': True, 'display_in_list': True},
                {'name': 'vaccine_type', 'label': 'Vaccine / Antigen', 'field_type': 'select',
                 'is_required': True, 'display_in_list': True,
                 'options': ['OPV', 'IPV', 'Penta', 'MCV1', 'MCV2', 'BCG',
                             'RVV', 'PCV', 'HPV', 'COVID-19', 'Other']},
                {'name': 'session_type', 'label': 'Session Type', 'field_type': 'select',
                 'is_required': True,
                 'options': ['Fixed', 'Outreach', 'Mobile Campaign']},
                {'name': 'target_population', 'label': 'Target Population',
                 'field_type': 'number', 'is_required': True},
                {'name': 'doses_administered', 'label': 'Doses Administered',
                 'field_type': 'number', 'is_required': True, 'display_in_list': True},
                {'name': 'doses_wasted', 'label': 'Doses Wasted', 'field_type': 'number'},
                {'name': 'defaulters', 'label': 'Defaulters', 'field_type': 'number'},
                {'name': 'cold_chain_equipment', 'label': 'Cold Chain Used',
                 'field_type': 'lookup', 'lookup_slug': 'imm_cold_chain'},
                {'name': 'conducted_by', 'label': 'Conducted By', 'field_type': 'text'},
                {'name': 'supervisor_present', 'label': 'Supervisor Present',
                 'field_type': 'boolean'},
                {'name': 'adverse_events_recorded', 'label': 'Any Adverse Events?',
                 'field_type': 'boolean'},
                {'name': 'notes', 'label': 'Notes', 'field_type': 'textarea'},
            ],
        },
        {
            'name': 'Adverse Event Report',
            'slug': 'imm_adverse_event',
            'description': 'Adverse events following immunization (AEFI)',
            'icon': '🚨',
            'is_lookup': False,
            'parent_slug': 'imm_vaccination_session',
            'fields': [
                {'name': 'event_date', 'label': 'Event Date', 'field_type': 'date',
                 'is_required': True, 'display_in_list': True},
                {'name': 'patient_age_months', 'label': 'Patient Age (months)',
                 'field_type': 'number', 'is_required': True},
                {'name': 'event_type', 'label': 'Severity', 'field_type': 'select',
                 'is_required': True, 'display_in_list': True,
                 'options': ['Mild', 'Moderate', 'Severe', 'Death']},
                {'name': 'symptoms', 'label': 'Symptoms / Description',
                 'field_type': 'textarea', 'is_required': True},
                {'name': 'hospitalised', 'label': 'Hospitalised', 'field_type': 'boolean'},
                {'name': 'outcome', 'label': 'Outcome', 'field_type': 'select',
                 'options': ['Recovered', 'Ongoing', 'Death', 'Unknown']},
                {'name': 'reported_to_national', 'label': 'Reported to National Programme',
                 'field_type': 'boolean'},
            ],
        },
    ],
    'forms': [
        {
            'name': 'Vaccination Session Report',
            'description': 'Record a vaccination session',
            'entity_type_slug': 'imm_vaccination_session',
            'fields': ['session_date', 'vaccine_type', 'session_type', 'target_population',
                       'doses_administered', 'doses_wasted', 'defaulters',
                       'cold_chain_equipment', 'conducted_by', 'supervisor_present',
                       'adverse_events_recorded', 'notes'],
        },
        {
            'name': 'Adverse Event Notification',
            'description': 'Report an AEFI (Adverse Event Following Immunization)',
            'entity_type_slug': 'imm_adverse_event',
            'fields': ['event_date', 'patient_age_months', 'event_type',
                       'symptoms', 'hospitalised', 'outcome', 'reported_to_national'],
        },
        {
            'name': 'Cold Chain Status Update',
            'description': 'Update cold chain equipment working status',
            'entity_type_slug': 'imm_cold_chain',
            'fields': ['working_status', 'last_temperature_check',
                       'min_temperature', 'max_temperature'],
        },
    ],
}
